apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yaook-cert-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: yaook
  source:
    repoURL: https://github.com/your-repo/yaook-operator-gitops
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: yaook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
