apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yaook
  namespace: argocd
spec:
  description: Yaook no-Ceph demo project
  destinations:
    - namespace: yaook
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: local-path-storage
      server: https://kubernetes.default.svc
    - namespace: harbor
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
